// export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';

// export const GET_USER_POSTS = 'GET_USER_POSTS';
export const GET_USER_POSTS_SUCCESS = 'GET_USER_POSTS_SUCCESS';
export const GET_USER_POSTS_ERROR = 'GET_USER_POSTS_ERROR';

// export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
export const GET_ALL_COMMENTS_SUCCESS = 'GET_ALL_COMMENTS_SUCCESS';
export const GET_ALL_COMMENTS_ERROR = 'GET_ALL_COMMENTS_ERROR';
